

server:
  port: 9898

spring:
  application:
    name: Classroom
  datasource:
    url: jdbc:mysql://localhost:3306/classroom
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate Properties
  jpa:
    hibernate:
      ddl-auto: create-drop
